### PR TITLE
Create editor.slf without the original

### PR DESCRIPTION
**Pull request by flaviojs**
Reference: #1

~It's failing in ETRLE right now, not sure why. Some help please.~

### CODE REVIEW

**Comment by flaviojs** [comment]
Was using python 2, it's building editor.slf now.
From a hex editor the contents of editor.slf seem fine, can you check if the resulting STI is valid?

**Comment by flaviojs** [comment]
Ok, decided to use python scripts instead of json to compose the images.
To simplify, I'm relying on the save capabilities introduced in ja2-stracciatella/ja2-open-toolset#8.

**Comment by flaviojs** [comment]
The good news: I can create a complete editor.slf and start the editor with it. Yay! \o/
The bad news: Seems like I misunderstood something about ETRLE compression:
editor

**Comment by lynxlynxlynx** [comment]
Nice progress!

**Comment by flaviojs** [comment]
When ja2-stracciatella/ja2-open-toolset#8 is merged, this can also be merged. ^^
editor

**Comment by lynxlynxlynx** [comment]
How big is the STI? We could probably bundle it by default, so editor access is easy for everyone.

**Comment by flaviojs** [comment]
The slf is 565.6 kB in size.
I think it's better to release it separately.
Currently most of it is placeholder images with text.

**Pull request merged**
